In [19]:
import numpy as np
import pandas as pd

dataset=pd.read_csv('english_french_1000_short_pairs.csv')
X=dataset.iloc[:,0].values
Y=dataset.iloc[:,1].values
dataset.isnull().sum()

,0
english,0
french,0


In [20]:
print(Y)

['Le chat est dans le jardin.' 'Le chat est à la maison.'
 "Le chat est dans l'école." 'Le chat est dans le parc.'
 'Le chat est dans la cuisine.' 'Le chat est dans la chambre.'
 'Le chat est dans la rue.' 'Le chat est à la gare.'
 'Le chat est dans le village.' 'Le chat est près de la rivière.'
 'Le chien est dans le jardin.' 'Le chien est à la maison.'
 "Le chien est dans l'école." 'Le chien est dans le parc.'
 'Le chien est dans la cuisine.' 'Le chien est dans la chambre.'
 'Le chien est dans la rue.' 'Le chien est à la gare.'
 'Le chien est dans le village.' 'Le chien est près de la rivière.'
 "L'oiseau est dans le jardin." "L'oiseau est à la maison."
 "L'oiseau est dans l'école." "L'oiseau est dans le parc."
 "L'oiseau est dans la cuisine." "L'oiseau est dans la chambre."
 "L'oiseau est dans la rue." "L'oiseau est à la gare."
 "L'oiseau est dans le village." "L'oiseau est près de la rivière."
 'Le lapin est dans le jardin.' 'Le lapin est à la maison.'
 "Le lapin est dans l'école."

In [21]:
for v,i in enumerate(Y):
  Y[v]="<start> "+Y[v]+" <end>"
Y

array(['<start> Le chat est dans le jardin. <end>',
       '<start> Le chat est à la maison. <end>',
       "<start> Le chat est dans l'école. <end>",
       '<start> Le chat est dans le parc. <end>',
       '<start> Le chat est dans la cuisine. <end>',
       '<start> Le chat est dans la chambre. <end>',
       '<start> Le chat est dans la rue. <end>',
       '<start> Le chat est à la gare. <end>',
       '<start> Le chat est dans le village. <end>',
       '<start> Le chat est près de la rivière. <end>',
       '<start> Le chien est dans le jardin. <end>',
       '<start> Le chien est à la maison. <end>',
       "<start> Le chien est dans l'école. <end>",
       '<start> Le chien est dans le parc. <end>',
       '<start> Le chien est dans la cuisine. <end>',
       '<start> Le chien est dans la chambre. <end>',
       '<start> Le chien est dans la rue. <end>',
       '<start> Le chien est à la gare. <end>',
       '<start> Le chien est dans le village. <end>',
       '<start> Le chie

In [22]:
from sklearn.model_selection import train_test_split

X_train_val,X_test,Y_train_val,Y_test=train_test_split(X,Y,test_size=0.10, random_state=42)

X_train,X_val,Y_train,Y_val=train_test_split(X_train_val,Y_train_val,test_size=0.10,random_state=42)

In [23]:
from tensorflow.keras.preprocessing.text import Tokenizer


# Initialize and fit the tokenizer
tokenizer_eng = Tokenizer(oov_token="<unk>")
tokenizer_eng.fit_on_texts(X_train)

tokenizer_fr = Tokenizer(oov_token="<unk>")
tokenizer_fr.fit_on_texts(Y_train)
# 1. Get token-to-ID mapping (Vocabulary)
print(tokenizer_fr.word_index)
# Output: {'python': 1, 'is': 2, 'great': 3, 'i': 4, 'love': 5, 'coding': 6, 'in': 7}

# 2. Get the token frequency dictionary
print(tokenizer_fr.word_counts)

X_train=tokenizer_eng.texts_to_sequences(X_train)
Y_train=tokenizer_fr.texts_to_sequences(Y_train)

X_val=tokenizer_eng.texts_to_sequences(X_val)
Y_val=tokenizer_fr.texts_to_sequences(Y_val)

X_test=tokenizer_eng.texts_to_sequences(X_test)
Y_test=tokenizer_fr.texts_to_sequences(Y_test)


{'<unk>': 1, 'start': 2, 'end': 3, 'le': 4, 'est': 5, 'une': 6, 'il': 7, 'dans': 8, 'un': 9, 'la': 10, 'a': 11, 'voit': 12, 'les': 13, 'cheval': 14, "l'enfant": 15, "l'ami": 16, 'je': 17, 'chien': 18, 'chat': 19, 'professeur': 20, "l'oiseau": 21, 'médecin': 22, 'lapin': 23, "l'étudiant": 24, 'téléphone': 25, 'lettre': 26, 'pomme': 27, 'livre': 28, 'balle': 29, 'sac': 30, 'carte': 31, 'clé': 32, 'fleur': 33, 'chaise': 34, 'à': 35, 'de': 36, 'gentil': 37, 'calme': 38, 'occupé': 39, 'cuisine': 40, 'heureux': 41, 'prends': 42, 'maison': 43, 'chambre': 44, 'trouve': 45, 'ferme': 46, "l'école": 47, 'rue': 48, 'jeune': 49, 'village': 50, 'fort': 51, 'en': 52, 'sécurité': 53, 'silencieux': 54, 'près': 55, 'rivière': 56, 'parc': 57, 'gare': 58, 'prêt': 59, 'jardin': 60, 'fatigué': 61, 'professeurs': 62, 'écrit': 63, 'attendent': 64, 'utilise': 65, 'travaillent': 66, 'médecins': 67, 'chiens': 68, 'garde': 69, 'amis': 70, 'lit': 71, 'ouvre': 72, 'veux': 73, 'montre': 74, 'chantent': 75, 'connais'

In [24]:
Y

array(['<start> Le chat est dans le jardin. <end>',
       '<start> Le chat est à la maison. <end>',
       "<start> Le chat est dans l'école. <end>",
       '<start> Le chat est dans le parc. <end>',
       '<start> Le chat est dans la cuisine. <end>',
       '<start> Le chat est dans la chambre. <end>',
       '<start> Le chat est dans la rue. <end>',
       '<start> Le chat est à la gare. <end>',
       '<start> Le chat est dans le village. <end>',
       '<start> Le chat est près de la rivière. <end>',
       '<start> Le chien est dans le jardin. <end>',
       '<start> Le chien est à la maison. <end>',
       "<start> Le chien est dans l'école. <end>",
       '<start> Le chien est dans le parc. <end>',
       '<start> Le chien est dans la cuisine. <end>',
       '<start> Le chien est dans la chambre. <end>',
       '<start> Le chien est dans la rue. <end>',
       '<start> Le chien est à la gare. <end>',
       '<start> Le chien est dans le village. <end>',
       '<start> Le chie

In [25]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Find sequence lengths using training data only
max_eng_len = max(
    max(len(sentence) for sentence in X_train),
    max(len(sentence) for sentence in X_val),
    max(len(sentence) for sentence in X_test)
)

max_fr_len = max(
    max(len(sentence) for sentence in Y_train),
    max(len(sentence) for sentence in Y_val),
    max(len(sentence) for sentence in Y_test)
)

# Pad English encoder inputs
X_train = pad_sequences(X_train, maxlen=max_eng_len, padding="post",truncating="post")
X_val   = pad_sequences(X_val,   maxlen=max_eng_len, padding="post",truncating="post")
X_test  = pad_sequences(X_test,  maxlen=max_eng_len, padding="post",truncating="post")

# Pad full French sequences, including <start> and <end>
Y_train = pad_sequences(Y_train, maxlen=max_fr_len, padding="post",truncating="post")
Y_val   = pad_sequences(Y_val,   maxlen=max_fr_len, padding="post",truncating="post")
Y_test  = pad_sequences(Y_test,  maxlen=max_fr_len, padding="post",truncating="post")

# Shift French sequences by one token
decoder_input_train = Y_train[:, :-1]
decoder_target_train = Y_train[:, 1:]

decoder_input_val = Y_val[:, :-1]
decoder_target_val = Y_val[:, 1:]

decoder_input_test = Y_test[:, :-1]
decoder_target_test = Y_test[:, 1:]



In [26]:
print(Y_train)
print(decoder_input_train)

[[ 2  4 23 ...  0  0  0]
 [ 2 13 62 ...  0  0  0]
 [ 2  4 18 ...  0  0  0]
 ...
 [ 2 13 67 ...  0  0  0]
 [ 2 13 88 ...  0  0  0]
 [ 2 24  5 ...  0  0  0]]
[[ 2  4 23 ...  0  0  0]
 [ 2 13 62 ...  0  0  0]
 [ 2  4 18 ...  3  0  0]
 ...
 [ 2 13 67 ...  0  0  0]
 [ 2 13 88 ...  0  0  0]
 [ 2 24  5 ...  0  0  0]]


In [27]:
print(max_eng_len, max_fr_len)
print(X_train.shape)
print(decoder_input_train.shape)
print(decoder_target_train.shape)

6 10
(810, 6)
(810, 9)
(810, 9)


In [28]:
eng_vocab_size = len(tokenizer_eng.word_index) + 1
fr_vocab_size = len(tokenizer_fr.word_index) + 1

In [29]:
import tensorflow as tf

d_model = 64

# True for real tokens; False for padding token 0
encoder_mask_train = tf.not_equal(X_train, 0)
decoder_mask_train = tf.not_equal(decoder_input_train, 0)

encoder_mask_val = tf.not_equal(X_val, 0)
decoder_mask_val = tf.not_equal(decoder_input_val, 0)

encoder_mask_test = tf.not_equal(X_test, 0)
decoder_mask_test = tf.not_equal(decoder_input_test, 0)

In [30]:
import tensorflow as tf
from tensorflow.keras.layers import Layer, Embedding

class PositionalEmbedding(Layer):
    def __init__(self, vocab_size, sequence_length, d_model):
        super().__init__()
        self.token_embedding = Embedding(
            input_dim=vocab_size,
            output_dim=d_model,
            mask_zero=False
        )
        self.position_embedding = Embedding(
            input_dim=sequence_length,
            output_dim=d_model
        )

    def call(self, inputs):
        length = tf.shape(inputs)[-1]
        positions = tf.range(start=0, limit=length, delta=1)

        token_vectors = self.token_embedding(inputs)
        position_vectors = self.position_embedding(positions)

        return token_vectors + position_vectors


In [31]:
eng_pos_embedding = PositionalEmbedding(
    eng_vocab_size, max_eng_len, d_model
)

fr_pos_embedding = PositionalEmbedding(
    fr_vocab_size, max_fr_len - 1, d_model
)

In [32]:
print(eng_pos_embedding(X_train[:2]).shape)
print(fr_pos_embedding(decoder_input_train[:2]).shape)

(2, 6, 64)
(2, 9, 64)


In [33]:
from tensorflow.keras.layers import (
    Dense, Dropout, LayerNormalization, MultiHeadAttention
)

ff_dim = 128
num_heads = 4
dropout_rate = 0.1

class EncoderBlock(Layer):
    def __init__(self, d_model, num_heads, ff_dim, dropout_rate=0.1):
        super().__init__()

        self.attention = MultiHeadAttention(
            num_heads=num_heads,
            key_dim=d_model // num_heads
        )

        self.ffn = tf.keras.Sequential([
            Dense(ff_dim, activation="relu"),
            Dense(d_model)
        ])

        self.norm1 = LayerNormalization()
        self.norm2 = LayerNormalization()
        self.dropout1 = Dropout(dropout_rate)
        self.dropout2 = Dropout(dropout_rate)

    def call(self, inputs, training=False, mask=None):
        attention_mask = None

        if mask is not None:
            attention_mask = mask[:, tf.newaxis, :]

        attention_output = self.attention(
            query=inputs,
            value=inputs,
            key=inputs,
            attention_mask=attention_mask,
            training=training
        )

        attention_output = self.dropout1(
            attention_output,
            training=training
        )

        x = self.norm1(inputs + attention_output)

        ffn_output = self.ffn(x)
        ffn_output = self.dropout2(ffn_output, training=training)

        return self.norm2(x + ffn_output)


In [34]:
encoder_block = EncoderBlock(
    d_model=d_model,
    num_heads=num_heads,
    ff_dim=ff_dim,
    dropout_rate=dropout_rate
)

english_with_position = eng_pos_embedding(X_train[:2])

encoder_output = encoder_block(
    english_with_position,
    mask=encoder_mask_train[:2]
)

print(encoder_output.shape)

(2, 6, 64)


/usr/local/lib/python3.13/dist-packages/keras/src/layers/layer.py:982: UserWarning: Layer 'encoder_block_1' (of type EncoderBlock) was passed an input with a mask attached to it. However, this layer does not support masking and will therefore destroy the mask information. Downstream layers will not see the mask.
  warnings.warn(


In [35]:
from tensorflow.keras.layers import (
    Layer, Dense, Dropout, LayerNormalization, MultiHeadAttention
)

class DecoderBlock(Layer):
    def __init__(self, d_model, num_heads, ff_dim, dropout_rate=0.1):
        super().__init__()

        self.self_attention = MultiHeadAttention(
            num_heads=num_heads,
            key_dim=d_model // num_heads,
            dropout=dropout_rate
        )

        self.cross_attention = MultiHeadAttention(
            num_heads=num_heads,
            key_dim=d_model // num_heads,
            dropout=dropout_rate
        )

        self.ffn = tf.keras.Sequential([
            Dense(ff_dim, activation="relu"),
            Dense(d_model)
        ])

        self.norm1 = LayerNormalization(epsilon=1e-6)
        self.norm2 = LayerNormalization(epsilon=1e-6)
        self.norm3 = LayerNormalization(epsilon=1e-6)

        self.dropout1 = Dropout(dropout_rate)
        self.dropout2 = Dropout(dropout_rate)
        self.dropout3 = Dropout(dropout_rate)

    def call(
        self,
        decoder_inputs,
        encoder_outputs,
        training=False,
        decoder_mask=None,
        encoder_mask=None
    ):
        # French masked self-attention
        decoder_attention_mask = None
        if decoder_mask is not None:
            decoder_attention_mask = decoder_mask[:, tf.newaxis, :]

        self_attention_output = self.self_attention(
            query=decoder_inputs,
            value=decoder_inputs,
            key=decoder_inputs,
            attention_mask=decoder_attention_mask,
            use_causal_mask=True,
            training=training
        )

        self_attention_output = self.dropout1(
            self_attention_output,
            training=training
        )

        x = self.norm1(decoder_inputs + self_attention_output)

        # English-to-French cross-attention
        encoder_attention_mask = None
        if encoder_mask is not None:
            encoder_attention_mask = encoder_mask[:, tf.newaxis, :]

        cross_attention_output = self.cross_attention(
            query=x,
            value=encoder_outputs,
            key=encoder_outputs,
            attention_mask=encoder_attention_mask,
            training=training
        )

        cross_attention_output = self.dropout2(
            cross_attention_output,
            training=training
        )

        x = self.norm2(x + cross_attention_output)

        # Feed-forward network
        ffn_output = self.ffn(x)
        ffn_output = self.dropout3(ffn_output, training=training)

        return self.norm3(x + ffn_output)

In [36]:
decoder_block = DecoderBlock(
    d_model=d_model,
    num_heads=num_heads,
    ff_dim=ff_dim,
    dropout_rate=dropout_rate
)

french_with_position = fr_pos_embedding(decoder_input_train[:2])

decoder_output = decoder_block(
    decoder_inputs=french_with_position,
    encoder_outputs=encoder_output,
    decoder_mask=decoder_mask_train[:2],
    encoder_mask=encoder_mask_train[:2]
)

print(decoder_output.shape)

(2, 9, 64)


In [37]:
from tensorflow.keras.layers import Input, Dense, Lambda
from tensorflow.keras.models import Model

# 1. Two raw token-ID inputs
english_input = Input(
    shape=(max_eng_len,),
    dtype="int32",
    name="english_input"
)

french_input = Input(
    shape=(max_fr_len - 1,),
    dtype="int32",
    name="french_decoder_input"
)

# 2. Padding masks: True for real token, False for token ID 0
encoder_mask = Lambda(
    lambda x: tf.not_equal(x, 0),
    name="encoder_padding_mask"
)(english_input)

decoder_mask = Lambda(
    lambda x: tf.not_equal(x, 0),
    name="decoder_padding_mask"
)(french_input)

# 3. English embedding → encoder
english_vectors = eng_pos_embedding(english_input)

encoder_output = encoder_block(
    english_vectors,
    mask=encoder_mask
)

# 4. French embedding → decoder
french_vectors = fr_pos_embedding(french_input)

decoder_output = decoder_block(
    decoder_inputs=french_vectors,
    encoder_outputs=encoder_output,
    decoder_mask=decoder_mask,
    encoder_mask=encoder_mask
)

# 5. Predict one French vocabulary score vector at every French position
output_logits = Dense(
    fr_vocab_size,
    name="french_token_logits"
)(decoder_output)

# 6. Create the full model
model = Model(
    inputs=[english_input, french_input],
    outputs=output_logits,
    name="english_to_french_transformer"
)

model.summary()

Model: "english_to_french_transformer"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ english_input       │ (None, 6)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ french_decoder_inp… │ (None, 9)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ encoder_padding_ma… │ (None, 6)         │          0 │ english_input[0]… │
│ (Lambda)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ positional_embeddi… │ (None, 6, 64)     │      6,592 │ english_input[0]… │
│ (PositionalEmbeddi… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ positional_embeddi… │ (None, 9, 64)     │      7,424 │ french_decoder_i… │
│ (PositionalEmbeddi… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ decoder_padding_ma… │ (None, 9)         │          0 │ french_decoder_i… │
│ (Lambda)            │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ encoder_block_1     │ (None, 6, 64)     │     33,472 │ positional_embed… │
│ (EncoderBlock)      │                   │            │ encoder_padding_… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ decoder_block_1     │ (None, 9, 64)     │     50,240 │ positional_embed… │
│ (DecoderBlock)      │                   │            │ decoder_padding_… │
│                     │                   │            │ encoder_padding_… │
│                     │                   │            │ encoder_block_1[… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ french_token_logits │ (None, 9, 107)    │      6,955 │ decoder_block_1[… │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 104,683 (408.92 KB)

 Trainable params: 104,683 (408.92 KB)

 Non-trainable params: 0 (0.00 B)

In [38]:
loss_function = tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits=True,
    reduction="none"
)

def masked_loss(y_true, y_pred):
    loss = loss_function(y_true, y_pred)

    mask = tf.cast(tf.not_equal(y_true, 0), loss.dtype)
    loss = loss * mask

    return tf.reduce_sum(loss) / tf.reduce_sum(mask)

def masked_accuracy(y_true, y_pred):
    predicted_ids = tf.argmax(y_pred, axis=-1, output_type=y_true.dtype)

    matches = tf.cast(tf.equal(y_true, predicted_ids), tf.float32)
    mask = tf.cast(tf.not_equal(y_true, 0), tf.float32)

    matches = matches * mask

    return tf.reduce_sum(matches) / tf.reduce_sum(mask)

In [39]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss=masked_loss,
    metrics=[masked_accuracy]
)

In [40]:
early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    x={
        "english_input": X_train,
        "french_decoder_input": decoder_input_train
    },
    y=decoder_target_train,
    validation_data=(
        {
            "english_input": X_val,
            "french_decoder_input": decoder_input_val
        },
        decoder_target_val
    ),
    epochs=30,
    batch_size=32,
    callbacks=[early_stopping]
)

Epoch 1/30
26/26 ━━━━━━━━━━━━━━━━━━━━ 28s 472ms/step - loss: 3.1356 - masked_accuracy: 0.3695 - val_loss: 2.0735 - val_masked_accuracy: 0.5187
Epoch 2/30
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.7311 - masked_accuracy: 0.5916 - val_loss: 1.2604 - val_masked_accuracy: 0.7301
Epoch 3/30
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0102 - masked_accuracy: 0.7934 - val_loss: 0.7140 - val_masked_accuracy: 0.8685
Epoch 4/30
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.5725 - masked_accuracy: 0.9081 - val_loss: 0.3942 - val_masked_accuracy: 0.9593
Epoch 5/30
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3365 - masked_accuracy: 0.9720 - val_loss: 0.2085 - val_masked_accuracy: 0.9937
Epoch 6/30
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2023 - masked_accuracy: 0.9924 - val_loss: 0.1162 - val_masked_accuracy: 1.0000
Epoch 7/30
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1288 - masked_accuracy: 0.9974 - val_loss: 0.0716 - val_masked_accuracy: 1.0000
Epoch 8/30
26/26 

In [41]:
test_results = model.evaluate(
    x={
        "english_input": X_test,
        "french_decoder_input": decoder_input_test
    },
    y=decoder_target_test,
    return_dict=True
)

print(test_results)

4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 535ms/step - loss: 0.0022 - masked_accuracy: 1.0000
{'loss': 0.0021607442758977413, 'masked_accuracy': 1.0}


In [44]:
def translate_english_to_french(english_sentence):
    # English sentence → padded encoder input
    english_sequence = tokenizer_eng.texts_to_sequences([english_sentence])

    english_sequence = pad_sequences(
        english_sequence,
        maxlen=max_eng_len,
        padding="post",
        truncating="post"
    )

    # Begin French generation with <start>
    start_id = tokenizer_fr.word_index["start"]
    end_id = tokenizer_fr.word_index["end"]

    generated_ids = [start_id]

    for _ in range(max_fr_len - 1):
        # Current generated French tokens → padded decoder input
        french_sequence = pad_sequences(
            [generated_ids],
            maxlen=max_fr_len - 1,
            padding="post",
            truncating="post"
        )

        # Predict scores for every French vocabulary token
        predictions = model.predict(
            {
                "english_input": english_sequence,
                "french_decoder_input": french_sequence
            },
            verbose=0
        )

        # Predict the next token at the current position
        current_position = len(generated_ids) - 1
        next_id = int(
            tf.argmax(predictions[0, current_position, :]).numpy()
        )

        # Stop once <end> is predicted
        if next_id == end_id or next_id == 0:
            break

        generated_ids.append(next_id)

    french_words = [
        tokenizer_fr.index_word.get(token_id, "<unk>")
        for token_id in generated_ids[1:]
    ]

    return " ".join(french_words)

In [45]:
print(translate_english_to_french("The cat is in the garden."))
print(translate_english_to_french("The student sees a phone."))

le chat est dans le jardin
l'étudiant voit un téléphone
